from __future__ import annotations

import json
from dataclasses import MISSING, fields
from pathlib import Path
from typing import Any, get_args, get_origin

from .config import AgentConfig, HubConfig, MCPServerConfig, RouteRule


REFERENCE_OMITTED_KEYS = {"supports_vision"}


def generate_config_reference() -> str:
    sections = [
        "# Agent Hub Config Reference",
        "",
        "Generated from `agent_hub.config` dataclasses. Do not edit this file by hand.",
        "",
        _section("Top-Level HubConfig Keys", HubConfig),
        _section("AgentConfig Keys", AgentConfig),
        _section("RouteRule Keys", RouteRule),
        _section("MCPServerConfig Keys", MCPServerConfig),
    ]
    return "\n".join(sections).rstrip() + "\n"


def documented_config_keys() -> set[str]:
    return {field.name for field in fields(HubConfig)}


def _section(title: str, cls: type[Any]) -> str:
    lines = [
        f"## {title}",
        "",
        "| Key | Type | Default |",
        "| --- | --- | --- |",
    ]
    for field in fields(cls):
        if field.name in REFERENCE_OMITTED_KEYS:
            continue
        lines.append(
            f"| `{field.name}` | `{_type_name(field.type)}` | `{_default_value(field)}` |"
        )
    return "\n".join(lines)


def _type_name(value: Any) -> str:
    origin = get_origin(value)
    if origin is None:
        return getattr(value, "__name__", str(value).replace("typing.", ""))
    args = ", ".join(_type_name(arg) for arg in get_args(value))
    return f"{getattr(origin, '__name__', str(origin))}[{args}]"


def _default_value(field: Any) -> str:
    if field.default is not MISSING:
        value = field.default
    elif field.default_factory is not MISSING:  # type: ignore[attr-defined]
        try:
            value = field.default_factory()  # type: ignore[misc]
        except TypeError:
            value = "<factory>"
    else:
        return "<required>"
    if isinstance(value, Path):
        return value.as_posix()
    if isinstance(value, str):
        return value or '""'
    return json.dumps(value, ensure_ascii=False, default=str)


def main() -> None:
    print(generate_config_reference(), end="")


if __name__ == "__main__":
    main()
